version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
      ExternalCatalogBaseUrl: http://localhost:8000
    ports:
      - "8000:80"
    container_name: eventcatalogApi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.1.10:8888
      ConnectionString: basket.data
    ports:
      - "8001:80"
    container_name: cartapievent
    networks:
      - backend
      - frontend
    depends_on:
      - basket.data
      - tokenserver
      - rabbitmq

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: events/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.1.10:8888
      DatabaseServer: mssqlserver
      DatabaseName: EventOrdersDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "8802:80"
    container_name: orderapievent
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver
      - rabbitmq



  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "3000:1433"
    container_name: eventsqlserver
    networks:
      - backend

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:6262      
    ports:
      - "8888:80"
    container_name: eventtokensapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: webeventshop
    environment:
      EventCatalogUrl: http://eventcatalog
      IdentityUrl: http://192.168.1.10:8888
      CallbackUrl: http://localhost:6262
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_GzAG1vaQSGryOQvp3Y5A7Gmp00HcHHqGvr
      StripePrivateKey: sk_test_SKiU2qLqJEbnIyNyuhCeia1J00a2hSQGRG
    ports:
      - "6262:80"
    networks:
      - frontend
    depends_on:
      - eventcatalog
      - cart
      - order
      - tokenserver

  basket.data:
    image: redis
    ports:
      - "7080:6379"
    container_name: basketdataevent      
    networks:
      - backend


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqevent
    hostname: myrabbitmqevent
    ports:
      - "15678:15672"
      - "5674:5672"
      - "5672:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend 

